-- helena-ink-0's container lost its GPU passthrough silently: nvidia-smi
-- inside it started answering "No devices were found", not a crash, while
-- helena-ink-9um on the same host, carrying the identical DeviceRequests,
-- kept seeing its card the whole time. The worker process never died and
-- kept polling on schedule; its own "do I have a GPU" answer had been decided
-- once and never asked again, so it silently stopped claiming any P5 job that
-- needed one. Six jobs sat pending for five hours. Nothing crashed, nothing
-- logged, and ink_workers -- the row 007 added so a blocked worker would not
-- look like an idle one -- had nowhere to say a GPU had gone missing either:
-- last_poll_at kept advancing right through it.
--
-- NULL means this worker has never answered nvidia-smi at all -- a CPU-only
-- ink worker, if one is ever deployed, has nothing here to probe. TRUE and
-- FALSE both mean a worker that does claim a GPU: a card nvidia-smi listed
-- just now, or one it did not, which is the state this column exists to
-- catch. Written on every poll, not only at startup -- see ink_worker.py's
-- worker_gpu_visible().
ALTER TABLE ink_workers ADD COLUMN IF NOT EXISTS gpu_visible BOOLEAN;
