"""A skip has to be a decision somebody made, not an accident.

The smoke stage passed green while every one of its 44 tests skipped. The suite
is gated on HELENA_E2E_USER and HELENA_PANEL_PASSWORD, CI set neither, and the
whole thing opted out and reported success. A deploy job and a verification job
both went green having verified nothing.

That is the failure this file exists to stop, and it is not fixed by
remembering to set the variables -- it is fixed by making the run refuse.

With HELENA_E2E_NO_SKIP=1:

  * a skip for a reason not on ALLOWED below is a failure;
  * a run where nothing passed is a failure, however many tests "succeeded" by
    skipping.

A blanket ban is not honest here, and pretending otherwise would trade one
false green for another. Two of these tests queue real GPU work and work-3
has no card; three more read pipeline history that a freshly deployed staging
environment genuinely does not have yet. Those are declared below, each with the
reason it is tolerable. Everything else -- above all "no credentials" -- is a
failure.
"""

from __future__ import annotations

import os
import re

import pytest

NO_SKIP = os.environ.get("HELENA_E2E_NO_SKIP") == "1"

# Every skip the suite is permitted to make, and why. A reason that is not here
# is a test opting out of work it was asked to do.
ALLOWED = [
    # Needs a GPU and about fifteen minutes. The staging host has no card, so
    # this is a statement about the machine rather than about the code. Run it
    # where there is one: HELENA_E2E_HEAVY=1 against gpu-1.
    re.compile(r"set HELENA_E2E_HEAVY=1"),
    # Pipeline history a new deployment has not produced yet. These assert the
    # shape of real data -- a human review, an execution result, an attempted
    # cell -- and there is nothing dishonest about having none on day one.
    # They stop being skipped as soon as the platform does any work.
    re.compile(r"no surface carries a human review"),
    re.compile(r"no attempt on this control plane carries an execution result"),
    re.compile(r"nothing has been attempted on \S+ on this deployment"),
    re.compile(r"no diagnosis available|no such sample"),
]


def _permitted(reason: str) -> bool:
    return any(pattern.search(reason) for pattern in ALLOWED)


@pytest.hookimpl(hookwrapper=True)
def pytest_runtest_makereport(item, call):
    outcome = yield
    report = outcome.get_result()
    if not (NO_SKIP and report.skipped):
        return
    # longrepr for a skip is (path, lineno, "Skipped: reason").
    reason = ""
    if isinstance(report.longrepr, tuple) and len(report.longrepr) == 3:
        reason = str(report.longrepr[2])
    else:
        reason = str(report.longrepr)
    if _permitted(reason):
        return
    report.outcome = "failed"
    report.longrepr = (
        f"{reason}\n\n"
        "This skip is not on the allowed list in tests/e2e/conftest.py, and "
        "HELENA_E2E_NO_SKIP=1 is set. A verification job that skips is a "
        "verification job that reports success without looking.\n"
        "Either make the test run -- credentials are generated by the pipeline, "
        "so 'no credentials' is a bug, not a condition -- or add the reason to "
        "ALLOWED with the argument for why it is tolerable."
    )


def pytest_terminal_summary(terminalreporter):
    """Nothing passing is the shape the original failure took.

    Every individual skip can be permitted and the run still prove nothing, so
    this is checked separately: a suite that ran against a deployment and
    asserted not one thing about it did not verify the deployment.
    """
    if not NO_SKIP:
        return
    passed = len(terminalreporter.stats.get("passed", []))
    if passed:
        return
    terminalreporter.write_sep(
        "=", "no test passed; the suite verified nothing", red=True)
    # Turn a green run red. pytest reads this back as the process exit code.
    terminalreporter._session.exitstatus = pytest.ExitCode.TESTS_FAILED
