"""Which reconciliation is "the first" cannot depend on a content digest.

Both stores anchor a mission's history on its earliest reconciliation:

    ORDER BY created_at, reconciliation_id LIMIT 1

and compare that row's manifest hash against what is derived now. If they
disagree, the derivation is declared CONTROL_INCOMPLETE.

`created_at` is written by `utc_now()`, which truncates to whole seconds. Two
reconciliations recorded in the same second therefore tie, and the tie is broken
by `reconciliation_id` -- a content digest whose sort order has no relationship
to insertion order. So "the first" is whichever hash happens to sort lower, and
it can differ from the row that was actually written first.

This surfaced as an intermittent test failure. It is not a test problem: the
same ordering decides a real verdict on the deployed control plane, and a
verdict that depends on a hash is a verdict that flips.

The fix is to order by something monotonic in insertion. SQLite has an implicit
rowid; PostgreSQL is given an identity column. The two stores use their own
idiom and answer the same.
"""

from __future__ import annotations

import os
import re
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "framework/stages/01-segmentation"))

SQLITE = (ROOT / "framework/stages/01-segmentation/fleet/store.py").read_text()
POSTGRES = (
    ROOT / "framework/stages/01-segmentation/fleet/postgres_store.py").read_text()
DDL = (ROOT / "framework/stages/01-segmentation/fleet/migrations"
       / "001_postgresql.sql").read_text()

AMBIGUOUS = re.compile(r"ORDER BY created_at,\s*reconciliation_id")


def test_neither_store_breaks_the_tie_on_a_digest() -> None:
    """The ordering itself, in both stores, by source."""
    offenders = []
    for name, source in (("store.py", SQLITE), ("postgres_store.py", POSTGRES)):
        for match in AMBIGUOUS.finditer(source):
            line = source[: match.start()].count("\n") + 1
            offenders.append(f"{name}:{line}")
    assert not offenders, (
        "these order a mission's reconciliations by a content digest, so which "
        "one is 'first' depends on a hash rather than on when it was written: "
        + ", ".join(offenders))


def test_the_check_would_catch_the_ordering_it_forbids() -> None:
    """Proven against the string it is meant to reject."""
    assert AMBIGUOUS.search("ORDER BY created_at,reconciliation_id LIMIT 1")
    assert AMBIGUOUS.search("ORDER BY created_at, reconciliation_id LIMIT 1")
    assert not AMBIGUOUS.search("ORDER BY created_at,reconciliation_seq LIMIT 1")


def test_postgresql_carries_a_monotonic_insertion_column() -> None:
    """PostgreSQL has no usable implicit row order, so it is given one."""
    body = DDL[DDL.index(
        "CREATE TABLE IF NOT EXISTS "
        "segment_first_letters_discovery_history_reconciliations_v19"):]
    body = body[: body.index(");")]
    assert "reconciliation_seq" in body, (
        "the reconciliations table has no monotonic insertion column, so "
        "PostgreSQL cannot answer which row was written first")
    assert "GENERATED" in body or "bigserial" in body.lower(), (
        "reconciliation_seq is not generated by the database, so it can be "
        "supplied by a caller and is not an insertion order")


DSN = os.environ.get("HELENA_TEST_DSN")


def _mission_rows(store, mission_id: str) -> list[str]:
    """The states of one mission's reconciliations, oldest first."""
    return store.first_letters_discovery_reconciliation_states(mission_id)


def test_same_second_rows_keep_their_insertion_order(tmp_path) -> None:
    """Two rows in one second: the order out is the order in, both times."""
    from fleet.store import FleetStore

    store = FleetStore(tmp_path / "fleet.sqlite")
    store.initialize()

    now = "2026-08-05T01:02:03Z"
    rows = [
        # Digests chosen so that sorting by reconciliation_id reverses the
        # insertion order: without a monotonic tie-break this test fails.
        ("zzzz-written-first", "COMPLETE"),
        ("aaaa-written-second", "CONTROL_INCOMPLETE"),
    ]
    with store.connect() as connection:
        for index, (reconciliation_id, state) in enumerate(rows):
            connection.execute(
                """INSERT INTO first_letters_discovery_history_reconciliations_v19
                   (reconciliation_id,mission_id,state,watermark_sha256,
                    manifest_json,manifest_sha256,fixed_units,reason,
                    reconciliation_json,reconciliation_sha256,created_at)
                   VALUES(?,?,?,?,?,?,?,?,?,?,?)""",
                (reconciliation_id, "mission-order", state, "w" * 64, "{}",
                 "m" * 64, 0, None, "{}", f"{index}" + "s" * 63, now))
        connection.commit()

    assert _mission_rows(store, "mission-order") == [
        "COMPLETE", "CONTROL_INCOMPLETE"], (
        "the row written first is not reported first, so 'the earliest "
        "reconciliation' is decided by a digest")
